{% set name = "onnx-ir" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/onnx_ir-{{ version }}.tar.gz
  sha256: d20f4864fd93b9b020c86fe441e41103b51b7fa7665669db90487013648b3a1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - onnx >=1.16
    - typing_extensions >=4.10
    - ml_dtypes

test:
  imports:
    - onnx_ir
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/onnx/ir-py
  summary: Efficient in-memory representation for ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
