{% set version = "0.2.1" %}

package:
  name: onnx-ir
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/onnx-ir/onnx_ir-{{ version }}.tar.gz
  sha256: 8b8b10a93f43e65962104de6070c43c5dacb0e3cdfefc7c8059dd83c9db64f35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - onnx >=1.16
    - typing_extensions >=4.10
    - ml_dtypes >=0.5.0
    - sympy >=1.13

test:
  imports:
    - onnx_ir
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/onnx/ir-py
  summary: Efficient in-memory representation for ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
